In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:

import numpy as np

In [8]:
a=np.array ([1,2,3,4,5]) #one dimensional array- each elements alone in an array is called zero dimension
print (a)
#one dimensional is a collection of zero dimensional arrays

[1 2 3 4 5]


In [10]:
#zero dimensional example- no list- only an element
c=np.array(43)
c


[1 2 3 4]


In [11]:
a=np.array ((1,2,3,4))
print(a)

[1 2 3 4]


In [13]:
to get the data type
d=[6,7,8,9]
print (type(d))

<class 'list'>


In [19]:
#two dimensional example
a=np.array ([[1,2,3],[2,3,4],[4,5,3]])
print(a)

[[1 2 3]
 [2 3 4]
 [4 5 3]]


In [21]:
a=np.array ([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print (a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
a=np.array (((1,2,3,4),(5,6,7,8),(9,10,11,12)))
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
#3 dimension example
a=np.array([[[1,2,3,4],[3,4,5,6],[3,6,7,8]],[[1,2,3,6],[3,6,4,5],[9,6,4,3]]])
print (a)

[[[1 2 3 4]
  [3 4 5 6]
  [3 6 7 8]]

 [[1 2 3 6]
  [3 6 4 5]
  [9 6 4 3]]]


In [30]:
a=np.array([[[5,4,6],[9,7,6],[8,4,3]],[[9,8,2,],[9,5,3],[9,5,3]],[[6,5,4],[9,6,5],[2,5,6]]])
print (a)

[[[5 4 6]
  [9 7 6]
  [8 4 3]]

 [[9 8 2]
  [9 5 3]
  [9 5 3]]

 [[6 5 4]
  [9 6 5]
  [2 5 6]]]


In [32]:
a=np.array((((2,3,4),(0,6,7)),((3,2,5),(9,2,3)), ((8,5,7),(9,2,3))))
print (a)

[[[2 3 4]
  [0 6 7]]

 [[3 2 5]
  [9 2 3]]

 [[8 5 7]
  [9 2 3]]]


In [34]:
#Ndim- an attribute which gives output as what the dimension is
a.ndim

3

In [40]:
#ndmin= an attribute to custom the dimension
np.array([1,2,3,4],ndmin=5)

array([[[[[1, 2, 3, 4]]]]])

In [41]:
np.array ([1,2,3,4],ndmin=2)

array([[1, 2, 3, 4]])

In [3]:
#2 dimensional
import numpy as np
a=np.array([[1,2],[2,3],[3,4],[4,5],[5,6],[6,7]])
print (a)

[[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]
 [6 7]]


In [5]:
a.ndim

2

In [7]:
a=np.array([[[1,2],[2,3]],[[3,4],[4,5]],[[5,6],[6,7]]])
print (a)

[[[1 2]
  [2 3]]

 [[3 4]
  [4 5]]

 [[5 6]
  [6 7]]]


In [9]:
a.ndim

3

In [15]:
a=np.array([2,3,4,5,5,6])
print(a)

[2 3 4 5 5 6]


In [17]:
#to access an element in one dimension
arr=np.array([1,2,3,4,5])
arr[2]

3

In [19]:
#access element in two dimension
arr2=np.array([[1,2,3,4],[4,5,6,7]])
arr2[0,2] #(index of first row, index of second row)

3

In [25]:
#2/5 matrix, find 3rd element in 
a=np.array ([[1,2,3,4,5],[6,7,8,9,10]])
a[1,2]

8

In [27]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3[1,0,1]

8

In [31]:
arr4=np.array([[[3,2,],[5,4]],[[4,6,],[7,6]]])
arr4[0,1,0]

5

In [33]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3[0,1,2]

6

In [37]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3[1,0,2]

9

In [41]:
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
c=a[1]+b[2]
print(c)

8


In [49]:
a=np.array([[1,2],[3,4],[3,2],[9,8]])
a[1,0]+a[3,1]

11

In [51]:
#to get last element in a one dimensional
arr=np.array([1,2,3,4,5])
arr[-1]


5

In [55]:
a=np.array([[1,2],[3,4],[3,2],[9,8]])
a[3,-1]

8

In [57]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3[0,1,-1]

6

In [61]:
#slicing 1D
arr=np.array([1,2,3,4,5])
arr[2:5]

array([3, 4, 5])

In [69]:
arr=np.array([1,2,3,4,5,6])
arr[1:6:2]

array([2, 4, 6])

In [71]:
#two dimensional slicing
a=np.array([[1,2],[3,4],[3,2],[9,8]])
a[0,:1]

array([1])

In [83]:

a=np.array([[1,2,3,4],[4,5,6,7],[6,7,5,4],[7,5,3,1]])
a[3,1:3]

array([5, 3])

In [91]:
array2=np.array([[1,2,3,4],[4,5,6,7],[5,7,8,9]])
array2[:,1:]

array([[2, 3, 4],
       [5, 6, 7],
       [7, 8, 9]])

In [95]:
a=np.array([[1,2,3,4],[4,5,6,7],[6,7,5,4],[7,5,3,1]])
a[3:,0:2]

array([[7, 5]])

In [111]:
array2=np.array([[1,2,3,4],[4,5,6,7],[5,7,8,9]])
array2[:,1: :2]

array([[2, 4],
       [5, 7],
       [7, 9]])

In [125]:
array2=np.array([[1,2,3,4,5],[6,7,5,7,8]])
array2[0,0::2]

array([1, 3, 5])

In [129]:
#shape- to get the rows and columns in a dimension
array2=np.array([[1,2,3,4],[4,5,6,7],[5,7,8,9]])
array2.shape

(3, 4)

In [137]:
array3=np.array([[[1,2],[3,4]],[[3,2],[5,6]]])
array3.shape

(2, 2, 2)

In [141]:
array3=np.array([[[1,2],[3,4]],[[3,2],[5,6]],[[3,4,],[8,6]]])
array3.shape 
#output shown: (dimensions inside,rows in each dimension, columns)

(3, 2, 2)

In [143]:
array3=np.array ([[[1,2,3,4,5],[2,3,4,5,6]],[[4,5,6,7,8],[7,8,9,6,5]],[[3,4,5,6,7],[6,5,4,3,2]],[[5,4,3,2,1],[7,6,5,4,6]]])
array3.shape

(4, 2, 5)

In [1]:
import numpy as np
fruits=np.array(['banana','mango','pineapple','apple'])
fruits.dtype

dtype('<U9')

In [3]:
#U-unicode string with maximum of 9 char


In [5]:
#to declare datatype initially
arr=np.array([1,2,3,4], dtype='f')
arr

array([1., 2., 3., 4.], dtype=float32)

In [7]:
#to convert the datatype
arr=np.array([1,2,3,4])
arr.astype('f')

array([1., 2., 3., 4.], dtype=float32)

In [9]:
arr=np.array(['hello','hi'])
arr.astype('i')

ValueError: invalid literal for int() with base 10: 'hello'

In [11]:
#view and copy
a=np.array(['ridha','ajeeba','naseef'])
b=a.copy()
print (a)
print(b)

['ridha' 'ajeeba' 'naseef']
['ridha' 'ajeeba' 'naseef']


In [13]:
a=np.array(['ridha','ajeeba','naseef'])
b=a.copy()
print (a)
print(b)
a[0]='ilyas'
print (a)
print(b)

['ridha' 'ajeeba' 'naseef']
['ridha' 'ajeeba' 'naseef']
['ilyas' 'ajeeba' 'naseef']
['ridha' 'ajeeba' 'naseef']


In [17]:
a=np.array(['ridha','ajeeba','naseef'])
b=a.copy()
c=a.view()

print (a)
print(b)
print (c)

a[0]='ilyas'
print (a)
print(b)
print (c)

['ridha' 'ajeeba' 'naseef']
['ridha' 'ajeeba' 'naseef']
['ridha' 'ajeeba' 'naseef']
['ilyas' 'ajeeba' 'naseef']
['ridha' 'ajeeba' 'naseef']
['ilyas' 'ajeeba' 'naseef']


In [19]:
a=np.array([1,2,3,4,5,6])
b=a.copy()
c=a.view()

a[1]=6
print (a)
print(b)
print(c)



[1 6 3 4 5 6]
[1 2 3 4 5 6]
[1 6 3 4 5 6]


In [23]:
print (c.base) #gives the data as it is- the view function
print (b.base) #gives none for copy

[1 6 3 4 5 6]
None


In [34]:
a=np.array([1,2,3,4,5], ndmin=5)
print (a)
a.shape


[[[[[1 2 3 4 5]]]]]


(1, 1, 1, 1, 5)

In [38]:
a=np.array([[1,2],[3,4]])
a.shape

(2, 2)

In [40]:
arr= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [48]:
arr= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [66]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [76]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
c=arr.reshape (1,3,4)
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [78]:
#to change back any dimension to one dimension- known as flattening
c.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [82]:
a=np.arange(1,100)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [86]:
a=np.arange (1,51,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [88]:
a=np.arange(25,76)
a

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75])

In [92]:
b=np.ones(4,dtype='int')
b

array([1, 1, 1, 1])

In [100]:
#two dimension
f=np.ones((4,3),dtype='int')
f

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [98]:
#three dimension
f=np.ones((4,3,2),dtype='int')
f

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [106]:
z=np.zeros(4,dtype='int')
z

array([0., 0., 0., 0.])

In [112]:
#two dimensional
z=np.zeros((4,3),dtype='int')
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [114]:
#three dimensional
x=np.zeros((4,3,5),dtype='int')
x

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [120]:
#to get the fraction between two numbers
a=np.linspace(0,1)
a

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [122]:
#to divide fraction into equal number of parts
a=np.linspace(0,1,5)
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [130]:
#to present data diagonally
a=np.array ([1,2,3,4,5])
c=np.diag(a)
c

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [1]:
import numpy as np
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
a=np.array ([1,2,3,4,5,6,7,8])
arr=a.reshape (2,4)
arr
print(arr.base)


[1 2 3 4 5 6 7 8]


In [172]:
a=np.arange(1,21)
arr=a.reshape (1,4,5)
arr

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [174]:
arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
#mathematical operations
#sum
arr=np.array([1,2,3,4,])
result=np.sum(arr)
result

In [7]:
import numpy as np
arr=np.array([[1,2],[3,4],[2,3],[5,6]])
a=np.sum(arr)
a


26

In [9]:
arr1=([[[1,2],[5,5]],[[4,3],[5,7]]])
a=np.sum(arr1)
a

32

In [13]:
arr=([1,2,3,4,5])
arr1=([1,2,3,4,5])
b=np.add(arr,arr1)
b

array([ 2,  4,  6,  8, 10])

In [7]:
import numpy as np
arr1=([[1,8],[9,4],[4,6]])
arr2=([[9,8],[7,6],[5,4]])
a=np.add(arr1,arr2)
a

array([[10, 16],
       [16, 10],
       [ 9, 10]])

In [19]:
arr1=([[[1,2],[3,4]],[[4,6],[7,6]]])
arr2=([[[6,8],[9,8]],[[6,5],[3,1]]])
b= np.sum(arr1+arr2)
b

79

In [21]:
#two dimension axis-0,1
arr=np.array([[1,2],
              [3,4],
              [2,3],
              [5,6]])
print (np.sum(arr,axis=0)) #horizontally 
print (np.sum(arr,axis=1)) #vertically      

[11 15]
[ 3  7  5 11]


In [23]:
#three dimension- axis-0,1
arr=np.array([[[1,2],[3,4]],
              [[9,8],[8,4]],
              [[2,3],[5,1]]])
print (np.sum(arr,axis=0))
print (np.sum(arr,axis=1))

[[12 13]
 [16  9]]
[[ 4  6]
 [17 12]
 [ 7  4]]


In [37]:
#subtraction
#multiplication
arr=([1,2,3,4,5])
arr1=([1,2,3,4,5])
print(np.subtract(arr,arr1))
print(np.multiply(arr,arr1))



[0 0 0 0 0]
[ 1  4  9 16 25]


In [29]:

arr=([[[1,2],[4,3]],[[6,5],[8,9]]])


4.75


In [39]:
#max() to get maximum
#min() to get minimum
#std() standard deviation
#mean() to get mean
arr=([[[1,2],[4,3]],[[6,5],[8,9]]])
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))
print(np.mean(arr))

9
1
2.6339134382131846
4.75


In [53]:
#how to iterate an array

a=([1,2,3,4,5,6])
i=0
for i in a:
    print (i)

1
2
3
4
5
6


In [75]:
a=([1,2,3,4,5,6])
b=2
for i in a:
    print (i+b)

3
4
5
6
7
8


In [79]:
a=([[1,2],[4,5],[6,5]])
i=0
for i in a:
    for x in i: 
        print(x)
    

1
2
4
5
6
5


In [81]:
#to iterate unknown number of items--nditer()
arr2=np.array([[1,2,3,4],
              [5,6,7,8]])
for i in np.nditer(arr2):
    print (i)
    

1
2
3
4
5
6
7
8


In [85]:
arr1=np.array([[[1,2],[3,4]],[[4,6],[7,6]]])
for i in np.nditer(arr1):
    print(i)

1
2
3
4
4
6
7
6


In [97]:
# to use the index- ndnumerate()
arr1=np.array=([1,2,3,4,5,6])
for id, i in np.ndenumerate(arr1):
    print(id,i)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6


TypeError: 'list' object is not callable

In [107]:
a=np.array([[1,2],[4,5],[6,5]])

TypeError: 'list' object is not callable

In [3]:
import numpy as np
arr1=np.array([[[1,2],[3,4]],[[4,6],[7,6]]])
for id, i in np.ndenumerate(arr1):
    print(id, i)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 4
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 6


In [7]:
#to join arrays-- concantenate()
#one dimension
arr=([1,2,3,4,5])
arr1=([2,3,4,5,6])
a=np.concatenate((arr,arr1))
a


array([1, 2, 3, 4, 5, 2, 3, 4, 5, 6])

In [21]:
#two dimension
arr4=([[6,7],[8,9]])
arr3=([[5,4],[5,3]])
a=np.concatenate((arr4,arr3), axis=1)
a

array([[6, 7, 5, 4],
       [8, 9, 5, 3]])

In [23]:
arr4=([[6,7],[8,9]])
arr3=([[5,4],[5,3]])
a=np.concatenate((arr4,arr3), axis=0)
a

array([[6, 7],
       [8, 9],
       [5, 4],
       [5, 3]])

In [17]:
# three dimension
arr5= ([[[3,4],[8,7]],[[9,3],[7,5]]])
arr6= ([[[7,5],[1,2]],[[6,3],[1,2]]])
a=np.concatenate((arr5,arr6), axis=1)
a

array([[[3, 4],
        [8, 7],
        [7, 5],
        [1, 2]],

       [[9, 3],
        [7, 5],
        [6, 3],
        [1, 2]]])

In [19]:
arr5= ([[[3,4],[8,7]],[[9,3],[7,5]]])
arr6= ([[[7,5],[1,2]],[[6,3],[1,2]]])
a=np.concatenate((arr5,arr6), axis=0)
a

array([[[3, 4],
        [8, 7]],

       [[9, 3],
        [7, 5]],

       [[7, 5],
        [1, 2]],

       [[6, 3],
        [1, 2]]])

In [ ]:
#stack-

In [5]:
import numpy as np
arr1=([[3,4],[5,6],[9,8],[3,6]])
arr2=([[2,4],[8,6],[8,4],[6,2]])
a=np.concatenate((arr1,arr2),axis=0)
a

array([[3, 4],
       [5, 6],
       [9, 8],
       [3, 6],
       [2, 4],
       [8, 6],
       [8, 4],
       [6, 2]])

In [7]:
arr1=([[3,4],[6,7],[9,2]])
arr2=([[5,6],[9,2],[4,5]])
a=np.concatenate((arr1,arr2),axis=1)
a

array([[3, 4, 5, 6],
       [6, 7, 9, 2],
       [9, 2, 4, 5]])

In [11]:
arr1=([3,4,9,5,7,6,3,4])
arr2=([4,5,6,7,5,4,2,1])
a=np.concatenate((arr1,arr2))
a


array([3, 4, 9, 5, 7, 6, 3, 4, 4, 5, 6, 7, 5, 4, 2, 1])

In [27]:
a=([3,2,4,5,6])
b=([4,3,5,6,7])
c=np.stack((a,b),axis=1)
c

array([[3, 4],
       [2, 3],
       [4, 5],
       [5, 6],
       [6, 7]])

In [35]:
a=([[2,3],[4,5]])
b=([[5,4,],[6,3]])
c=np.hstack((a,b))
c

array([[2, 3, 5, 4],
       [4, 5, 6, 3]])

In [37]:
a=([[2,3],[4,5]])
b=([[5,4,],[6,3]])
c=np.vstack((a,b))
c

array([[2, 3],
       [4, 5],
       [5, 4],
       [6, 3]])

In [55]:
arr=np.array([1,2,3,4,5,6])
a=np.array_split(arr,4)
print(a)
b=a[0]
b

[array([1, 2]), array([3, 4]), array([5]), array([6])]


array([1, 2])

In [41]:
arr=np.array([1,2,3,4,5,6])
a=np.array_split(arr,3)
a

[array([1, 2]), array([3, 4]), array([5, 6])]

In [43]:
arr=np.array([1,2,3,4,5,6])
a=np.array_split(arr,2)
a

[array([1, 2, 3]), array([4, 5, 6])]

In [61]:
a=([[3,4,5,6],[8,7,6,5],[7,3,4,5]])
arr=np.array_split(a,3)
arr

[array([[3, 4, 5, 6]]), array([[8, 7, 6, 5]]), array([[7, 3, 4, 5]])]

In [67]:
a=np.array([[3,4,5,3],[5,4,5,6],[9,3,4,5]])
np.array_split(a,2,axis=1)

[array([[3, 4],
        [5, 4],
        [9, 3]]),
 array([[5, 3],
        [5, 6],
        [4, 5]])]

In [ ]:
vstack-- full details of a person-- horizontally full details-- column wise details
hstack-- particular detail of all persons-- vertically full details-- row wise details
vsplit and hsplit goes the same way


In [ ]:
where()-- to search an array

In [73]:
a=np.array([1,2,3,4,5,6,5,5])
b=np.where(a==5)
b

(array([4, 6, 7], dtype=int64),)

In [75]:
a=np.array([2,3,4,5,6,7])
b=np.where(a%2==0)
b

(array([0, 2, 4], dtype=int64),)

In [77]:
a=np.array([[2,3],[4,5],[6,7]])
b=np.where(a%2==0)
b

(array([0, 1, 2], dtype=int64), array([0, 0, 0], dtype=int64))

In [7]:
import numpy as np
#for an if condition
#np.where(condition, if true, if false
arr=np.array([1,2,3,4,5])
np.where(arr<=3,0,arr)


array([0, 0, 0, 4, 5])

In [105]:
a=np.array([1,2,3,4,5,6])
b=np.searchsorted(a,5,side='right')
b

5

In [109]:
a=np.array([2,1,3,3,8,5])
b=np.sort(a)
b

array([1, 2, 3, 3, 5, 8])

In [111]:
a=np.array(['apple','papaya','kiwi'])
b=np.sort(a)
b

array(['apple', 'kiwi', 'papaya'], dtype='<U6')

In [9]:
a=np.array([[1,2],[55,4],[6,5]])
b=np.sort(a)
b

array([[ 1,  2],
       [ 4, 55],
       [ 5,  6]])

In [11]:
#filter in numpy
a=np.arange(1,11)
filter_arr=[]
for i in a:
    if i%2==0:
        filter_arr.append(True)
    else:
        filter_arr.append (False)
array=a[filter_arr]
array

array([ 2,  4,  6,  8, 10])

In [15]:
a=np.arange(1,51)
arr=[]
for i in a:
    if i%2!=0:
        arr.append (True)
    else:
        arr.append (False)
b=a[arr]
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [17]:
#random
#rand()-- to select any random numbers between 0 and 1
arr=np.random.rand()
arr

0.609593985126162

In [19]:
arr=np.random.rand(5)
arr

array([0.49309687, 0.15073211, 0.42799449, 0.57023258, 0.65800865])

In [34]:
#randint ()- to select any random integers in float
#(start, end, size of arr)
arr=np.random.randint(1,90,5)
arr

array([83, 52,  9, 63, 44])

In [38]:
#to get a random number initially and not change when refreshed used the function
#seed()
np.random.seed(42) #(the bracket can be provided with any number, it has no effect on output
np.random.randint(1,70,10)
#when 42 is given in bracket, 42 is assigned with these set of numbers in output
#these set of numbers cant be changed when 42 is called again but can be randomly called within the set


array([52, 15, 61, 21, 24,  3, 22, 53,  2, 30])

In [42]:
#to get float numbers from a range of given numbers
np.random.uniform(5,10,5)

array([5.90912484, 5.91702255, 6.52121121, 7.62378216, 7.15972509])

In [44]:
np.random.uniform(10,101,20)

array([36.50185176, 65.67861342, 22.69394132, 36.58516302, 43.33892774,
       51.50236856, 81.45101249, 28.17031418, 56.7953339 , 63.90972577,
       14.22698756, 65.28658152, 25.51769526, 15.91969496, 96.34858389,
       97.87251501, 83.56415868, 37.71985299, 18.88816237, 72.26520541])

In [46]:
#randn()- to get normal distribution data from given range
np.random.randn(100)

array([-1.02155219, -0.16175539, -0.5336488 , -0.00552786, -0.22945045,
        0.38934891, -1.26511911,  1.09199226,  2.77831304,  1.19363972,
        0.21863832,  0.88176104, -1.00908534, -1.58329421,  0.77370042,
       -0.53814166, -1.3466781 , -0.88059127, -1.1305523 ,  0.13442888,
        0.58212279,  0.88774846,  0.89433233,  0.7549978 , -0.20716589,
       -0.62347739, -1.50815329,  1.09964698, -0.17773212, -0.41038331,
        1.17971634, -0.89820794,  0.83479542,  0.29656138, -1.03782988,
       -0.07580375,  0.97296353,  0.79559546,  1.49543425,  0.33818125,
        3.37229625, -0.92039081, -0.39863839, -0.06086409, -1.41875046,
        1.04249162,  0.90353249,  0.01900033, -0.53441645, -1.49505387,
       -0.78925833,  0.74371128, -0.21216142, -0.42686879,  0.50144833,
        1.15818665,  0.25711687,  0.3145129 ,  1.37186213,  0.17555329,
       -0.30928855,  0.6731255 , -0.25663018, -0.36782572,  1.27373362,
       -0.29195267, -2.65517605,  0.34551794, -0.39551645, -0.28

In [52]:
#to get shuffled data from given array
a=([1,2,3,4,5,6,7])
np.random.shuffle(a)
a

[1, 6, 4, 5, 7, 2, 3]