# TASK ONE

In [ ]:
import numpy as np

In [10]:
Question 3
give an array and print the index number
a=([12,3,3,44,5])
print(a[3])

44


In [18]:
import numpy as np
Question 4
use arange() function
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [24]:
Question 5
a=np.array([1,2,3,4,5])
a.reshape(2,3)
the error printed would be that the array cannot be reshaped into (2,3)

ValueError: cannot reshape array of size 5 into shape (2,3)

In [28]:
Question 6
arr=np.array([10,20,30,40,50])
print (arr[2])

30


In [36]:
Question 7
a=np.array([[[1,2,3],[5,4,6],[6,2,1]],[[4,3,5],[7,5,6],[2,1,4]],[[8,9,0],[3,4,5],[5,7,9]]])
print (a[1,2,2])

4


In [44]:
Question 8
a=np.array([[1,2,3],[4,5,6]])
a.ndim

2

In [50]:
Question 9
arr=np.array([[1,2,3],[9,7,5]])
print(arr[1,2])

5


In [9]:
# Question 10
arr=np.array([[1,2,3,4],[5,6,7,8]], ndmin=6)
# arr.reshape(2,4)
print(arr)

print(arr.shape)

[[[[[[1 2 3 4]
     [5 6 7 8]]]]]]
(1, 1, 1, 1, 2, 4)


In [84]:
#Question 11
arr=np.array([1,2,3,4,5])
arr[-1]=100
arr


array([  1,   2,   3,   4, 100])

In [15]:
#Question 12
arr1=np.array([1,2,3,4,5,6,7,8,9])
# arr2=np.where(a%2==0)
# arr2
arr2=arr1%2==0
print(arr2)
print(arr1[arr2])

[False  True False  True False  True False  True False]
[2 4 6 8]


In [102]:
#Question 13
a=np.array([1,2,3,4,5])
print(a[2])

3


In [11]:
Question 14
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=np.where (a<3,-3,a)
print(c)
np.hstack((a,b))

[-3 -3  3  4  5]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#Question 15
import numpy as np
a=np.arange(0,10,0.5)
b=[]
for i in a:
    if i<=5:
        b.append(False)
    else:
        b.append(True)
c=a[b]
c

array([5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])