In [ ]:
NUMPY STACK
Numpy’s stack function is used to stack/join arrays along a new axis. In simple words, it is combining multiple arrays along a new axis to create a single array. This is different from concatenation, which joins arrays end-to-end along an existing axis. 
The main objective of stack would involve the efficient joining of several arrays into a single larger array which is useful when working with multiple pieces of data as a whole unit, it would also introduce a new dimension to the resulting array which would in a way help organize the combined data.
STACK VS CONCATENATION
•	Stack: Imagine stacking plates on top of each other. Each plate represents an array, and the stack creates a new dimension (height) to organize them.
•	Concatenation: Imagine placing plates side-by-side on a table. You're joining them along an existing dimension (length of the table).
CHOOSING BETWEEN STACK AND CONCATENATION:
The choice depends on your desired outcome:
•	If you want to combine arrays with a new level of organization, use stack.
•	If you simply want to join arrays along an existing dimension, use concatenate.



In [1]:
import numpy as np

#STACKING OF 1D ARRAY

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.array([7, 8, 9])

stacked_1d_axis0 = np.stack((array1, array2, array3), axis=0)
print(stacked_1d_axis0)

stacked_1d_axis1 = np.stack((array1, array2, array3), axis=1)
print(stacked_1d_axis1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [3]:
#STACKING OF 2D ARRAY
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
array3 = np.array([[9, 10], [11, 12]])

stacked_2d_axis0 = np.stack((array1, array2, array3), axis=0)
print(stacked_2d_axis0)

stacked_2d_axis1 = np.stack((array1, array2, array3), axis=1)
print(stacked_2d_axis1)



[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[[[ 1  2]
  [ 5  6]
  [ 9 10]]

 [[ 3  4]
  [ 7  8]
  [11 12]]]


In [7]:
#STACKING OF 3D ARRAY
array1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array2 = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])
array3 = np.array([[[17, 18], [19, 20]], [[21, 22], [23, 24]]])


stacked_3d_axis0 = np.stack((array1, array2, array3), axis=0)
print( stacked_3d_axis0)

stacked_3d_axis1 = np.stack((array1, array2, array3), axis=1)
print( stacked_3d_axis1)



[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]


 [[[17 18]
   [19 20]]

  [[21 22]
   [23 24]]]]
[[[[ 1  2]
   [ 3  4]]

  [[ 9 10]
   [11 12]]

  [[17 18]
   [19 20]]]


 [[[ 5  6]
   [ 7  8]]

  [[13 14]
   [15 16]]

  [[21 22]
   [23 24]]]]


In [ ]:
vstack (vertical stack):

    It stacks arrays vertically, like placing them on top of each other.

In [15]:
import numpy as np
#1D example
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=np.vstack ((a,b))
c

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
#2D example
a = np.array([[1, 2, 3], [4, 5, 6]])

b = np.array([[7, 8, 9],[10, 11, 12]])
c=np.vstack((a,b))
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
#3D example

a = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])

b = np.array([[[13, 14, 15],[16, 17, 18]],[[19, 20, 21],[22, 23, 24]]])
c= np.vstack ((a,b))
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [ ]:
hstack (horizontal stack):

    It stacks arrays horizontally, like placing them side by side.

In [21]:
#1D example
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=np.hstack ((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [23]:
#2D example
a = np.array([[1, 2, 3],[4, 5, 6]])

b = np.array([[7, 8, 9],[10, 11, 12]])
c=np.hstack((a,b))
c

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [3]:
#3D example
import numpy as np
a = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])

b = np.array([[[13, 14, 15],[16, 17, 18]],[[19, 20, 21],[22, 23, 24]]])
c= np.hstack ((a,b))
c

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [13, 14, 15],
        [16, 17, 18]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [19, 20, 21],
        [22, 23, 24]]])

In [23]:
!pip install nbconvert

In [25]:
! jupyter nbconvert --to pdf Numpy Stack.ipynb

SyntaxError: invalid syntax (3785494031.py, line 1)