In [5]:
import numpy as np


In [13]:
#question 1
arr=np.random.randint (10,50,24)
print(arr)
arr.reshape(2,3,4)

[21 14 10 48 17 10 43 31 20 10 46 45 22 20 20 18 36 14 14 49 39 32 20 20]


array([[[21, 14, 10, 48],
        [17, 10, 43, 31],
        [20, 10, 46, 45]],

       [[22, 20, 20, 18],
        [36, 14, 14, 49],
        [39, 32, 20, 20]]])

In [9]:
import numpy as np

#Question 2
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.add (a,b))
print(np.subtract (a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [15]:
Question 3
a=np.ones((3,3),dtype='int')
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [21]:
#Question 4
a=np.array([1,2,3,4,5,6,7,8,9])
a.reshape(3,3)
a.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
#Question 5
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.vstack ((a,b))
d=np.hstack((a,b))
c,d

(array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]),
 array([[1, 2, 5, 6],
        [3, 4, 7, 8]]))

In [35]:
#question 6
a=np.array([1,2,3,4,5,6,7,8,9,10])
b=np.array_split(a,2)
b

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [39]:
#Question 7
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=a[1]
b

array([4, 5, 6])

In [109]:
#Question 8
a=np.array([10,20,30,40,50],ndmin=3)
print(a[0,2,4])


IndexError: index 2 is out of bounds for axis 1 with size 1

In [53]:
#Question 9
a=np.array([1,2,3,4,5])
print(np.mean(a))
print(np.sum(a))
print(np.std(a))

3.0
15
1.4142135623730951


In [57]:
#Question 10
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print (np.min(a))
print(np.max(a))

1
9


In [77]:
#Question 11
a=np.array([[3,1,4],[1,5,9]])
b=np.array([[2,6,5],[7,8,0]])
c=np.sort(a)
d=np.sort(b)
print(np.hstack((a,b)))

[[3 1 4 2 6 5]
 [1 5 9 7 8 0]]


In [85]:
#Question 12
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.where(a<3))
print(np.where(a>7))

(array([0, 1], dtype=int64),)
(array([7, 8, 9], dtype=int64),)


In [91]:
#question 13
a=np.array([[30,32,31,29,28,30,31],[25,26,27,28,29,30,31]])
print(np.where(a>30))
b=np.hstack((a))
b


(array([0, 0, 0, 1], dtype=int64), array([1, 2, 6, 6], dtype=int64))


array([30, 32, 31, 29, 28, 30, 31, 25, 26, 27, 28, 29, 30, 31])

In [ ]:
#Question 14
a=np.array([[100,101,102,103,104],[200,201,202,203,204]])

In [97]:
#Question 15
a=np.arange(1,30)
arr=[]
for i in a:
    if i%3==0:
        arr.append(True)
    else:
        arr.append (False)
array=a[arr]
array

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])